### ISSUE TITLE
PurchaseCooldown value = 0

### ISSUE THREAD

**Issue by adaneslavo** [Infixo/Civ5-Mods#1]
All VPEE units have PurchaseCooldown value = 0, while VP units have it set to one. I just corrected same values in MUCfVP, and I think you should do the same.

**Comment by Infixo** [comment]
@adaneslavo What does it do? Do you know?

**Comment by adaneslavo** [comment]
I suppose it blocks possibility of purchasing few units with gold in the same turn (with "1" you can buy one unit per turn). There's also another one GlobalFaithPurchaseCooldown which does the same with Great People and is set in VP on 5 (one unit per 5 turns). But I'm not sure on 100%. I just set value same like in whole VP. Mercenaries have zeros.

**Comment by Infixo** [comment]
Actually, all VPEE units have PurchaseCooldown = 1. Only 2-Hander has 0.
